### ISSUE TITLE
Why build Haskell code with optimizations turned off?

### ISSUE THREAD

**Issue by FranklinChen** [ConcordResearch/LanguageComparison#2]
```
stack build --fast; time stack run
```

Why is the Haskell code being built with Stack `--fast`, which turns off all optimizations (it is equivalent to running the compiler at optimization level `-O0`) and probably results in at least 10-fold slowdown in the generated program.

**Comment by gregberns** [comment]
In PR #1 someone brought that up but looks like it got put in two places. Changed now. Thanks

**Comment by FranklinChen** [comment]
Is the table of timing measurements up to date with respect to the correct build with optimization?

**Comment by gregberns** [comment]
I doubt it. We haven't run any of the tests since probably January. If you'd like to re-run and submit a PR with your times, I'll accept it.
